tasks:
  - name: Versions
    command: |
      sh ./tools/environment/versions.sh
  - name: Variables
    command: |
      sh ./tools/environment/variables.sh
  - name: Trunk
    command: |
      sh curl https://get.trunk.io -fsSL | bash

vscode:
  extensions:
    - formulahendry.code-runner
