name: add-issue-to-project
permissions:
  contents: read
on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.1
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: ${{ vars.TEMPLATE_TEAM_PROJECT }}
          github-token: ${{ secrets.WORK_MANAGEMENT }}